# Generated by Django 4.1.6 on 2023-04-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teatro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='movie/images/')),
                ('horario', models.TimeField()),
            ],
        ),
    ]
